import { NextResponse } from "next/server";
import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType,
} from "docx";
import { requireWorkspaceOwner } from "../../../../lib/requestAuth";

export const dynamic = "force-dynamic";

const isUuid = (value) =>
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(String(value || ""));

const text = (value) => String(value ?? "");

const paragraph = (value, options = {}) =>
  new Paragraph({
    ...options,
    children: [new TextRun(text(value))],
  });

const cell = (value) =>
  new TableCell({
    children: [paragraph(value)],
  });

const markdownToParagraphs = (content) =>
  text(content)
    .split(/\n+/)
    .map((line) => line.trim())
    .filter(Boolean)
    .map((line) => {
      if (line.startsWith("#")) {
        return new Paragraph({
          heading: HeadingLevel.HEADING_3,
          children: [new TextRun(line.replace(/^#+\s*/, ""))],
        });
      }
      return paragraph(line);
    });

export async function GET(request) {
  try {
    const { searchParams } = new URL(request.url);
    const workspaceId = searchParams.get("workspaceId");

    if (!isUuid(workspaceId)) {
      return NextResponse.json(
        { error: "A valid workspaceId UUID is required." },
        { status: 400 }
      );
    }

    const ownership = await requireWorkspaceOwner(request, workspaceId);
    if (ownership.errorResponse) return ownership.errorResponse;

    const { supabase } = ownership;
    const [
      { data: workspace, error: workspaceError },
      { data: drafts, error: draftsError },
      { data: requirements, error: requirementsError },
      { data: score, error: scoreError },
    ] = await Promise.all([
      supabase.from("rfp_workspaces").select("*").eq("id", workspaceId).single(),
      supabase.from("proposal_drafts").select("*").eq("workspace_id", workspaceId).order("created_at", { ascending: true }),
      supabase.from("rfp_requirements").select("*").eq("workspace_id", workspaceId).order("created_at", { ascending: true }),
      supabase.from("win_scores").select("*").eq("workspace_id", workspaceId).maybeSingle(),
    ]);

    if (workspaceError) throw workspaceError;
    if (draftsError) throw draftsError;
    if (requirementsError) throw requirementsError;
    if (scoreError) throw scoreError;

    const title = workspace?.title || "BidEngine Proposal";
    const complianceRows = [
      new TableRow({
        children: ["Requirement", "Status", "Confidence", "Evidence"].map((header) =>
          new TableCell({
            children: [
              new Paragraph({
                children: [new TextRun({ text: header, bold: true })],
              }),
            ],
          })
        ),
      }),
      ...(requirements || []).map((requirement) =>
        new TableRow({
          children: [
            cell(requirement.requirement_text),
            cell(String(requirement.compliance_status || "partial").toUpperCase()),
            cell(requirement.match_confidence === null || requirement.match_confidence === undefined ? "N/A" : `${requirement.match_confidence}%`),
            cell(requirement.matched_evidence || requirement.extracted_value || "No evidence mapped"),
          ],
        })
      ),
    ];

    const scoreLines = score
      ? [
          `Win Probability: ${score.total_score}%`,
          `GO/NO-GO Decision: ${score.decision}`,
          `Budget Alignment: ${score.budget_alignment}%`,
          `Capability Match: ${score.capability_match}%`,
          `Compliance Score: ${score.compliance_score}%`,
          `Sector Win Rate: ${score.sector_win_rate ?? "N/A"}%`,
          `Evaluation History Score: ${score.evaluation_history_score ?? "N/A"}%`,
          `Technical History Score: ${score.technical_history_score ?? "N/A"}%`,
          `Commercial History Score: ${score.commercial_history_score ?? "N/A"}%`,
          `Strategic Fit Score: ${score.strategic_fit_score ?? "N/A"}%`,
          `Risk Penalty Score: ${score.risk_penalty_score ?? "N/A"}%`,
        ]
      : ["Win score has not been calculated yet."];

    const sections = [
      {
        children: [
          new Paragraph({
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            children: [new TextRun(title)],
          }),
          paragraph(`Generated by BidEngine AI on ${new Date().toLocaleString()}`, {
            alignment: AlignmentType.CENTER,
          }),
          paragraph(" "),
          new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun("Proposal Draft")] }),
          ...((drafts || []).length
            ? drafts.flatMap((draft) => [
                new Paragraph({ heading: HeadingLevel.HEADING_2, children: [new TextRun(draft.section_title)] }),
                ...markdownToParagraphs(draft.content),
                paragraph(" "),
              ])
            : [paragraph("No proposal draft sections are available yet.")]),
          new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun("Compliance Checklist")] }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows: complianceRows,
          }),
          paragraph(" "),
          new Paragraph({ heading: HeadingLevel.HEADING_1, children: [new TextRun("Win Probability")] }),
          ...scoreLines.map((line) => paragraph(line)),
        ],
      },
    ];

    const doc = new Document({ sections });
    const buffer = await Packer.toBuffer(doc);
    const safeName = title.replace(/[^a-z0-9]+/gi, "-").replace(/^-|-$/g, "").slice(0, 80) || "proposal";

    return new NextResponse(buffer, {
      status: 200,
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${safeName}-proposal.docx"`,
        "Cache-Control": "no-store",
      },
    });
  } catch (err) {
    console.error("Proposal export failure:", err);
    return NextResponse.json(
      { error: "Failed to export proposal document: " + err.message },
      { status: 500 }
    );
  }
}
